### ISSUE TITLE
Please circuit Diagram 

### ISSUE THREAD

**Issue by Chahalb2010** [riquenunes/vw-steering-wheel-gamepad#1]
Hi,
I am trying to make esp32 simracing setup.
Please upload circuit Diagram and code with details.
I am using Arduino IDE.
I am a beginner so please help me.

**Comment by riquenunes** [comment]
Hey friend, I've updated the README to include a wiring diagram and the specific parts I've used. I hope it helps.

**Comment by Chahalb2010** [comment]
Thank you very much 😊
